import type { Metadata } from "next";
import { Toaster } from "react-hot-toast";

import "./globals.css";
import { StateContext } from "@/components/context/stateContext";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <StateContext>
          <Toaster /> {children}
        </StateContext>
      </body>
    </html>
  );
}
